# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b08001a7166fff7f419bb5f6270236db466984b3702ab463ba0b1fe47e69e1676770a137200cfc7f9839ba000d6ccedaec72a27f8b9bf83b2a3676fff53e333

test:
  secret_key_base: 991d32848287283d8cda66de77df84594ecec3c63aa6d192ff35fb51a0523a506017c46b5af0ec95650123ef337acc52c63ddd7552c8dad44392196ead1a15b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
